name: autogis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib-base
  - geopandas
  - folium
  - shapely
  - fiona
  - pyproj
  - rtree
  - rasterio
  - gdal
  - ipykernel
  - ipython
  - jinja2
  - requests
  - tqdm
  - pip
  - pip:
    - jupyterlab-git
