name: autogis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib-base
  - geopandas
  - folium
  - shapely
  - fiona
  - pyproj
  - rtree
  - osmnx
  - scipy
  - scikit-learn
  - pillow
  - requests
  - tqdm
  - ipykernel
  - ipython
  - jinja2
  - psycopg2
  - rasterio
  - gdal
  - sqlalchemy
  - attrs
  - matplotlib-inline
  - seaborn
  - contextily
  - pygeos
  - typing-extensions
  - packaging
  - pip
  - pip:
    - jupyterlab-git
    - geopandas
    - pandas
